# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider :virtualbox do |vb|
	vb.name = "ansiblesupplied"
	config.vm.provision "ansible_local" do |ansible|
		ansible.playbook = "playbook.yml"
	  end
  end
end
